jobs:
  include:
    - language: python
      python:
        - "3.5"
        - "3.6"      # current default Python on Travis CI
      # command to install dependencies
      install:
        - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
        - pip install git+https://github.com/pmla/evgraf@$BRANCH
      # command to run tests
      script:
        - pytest tests/*
